# 1. MySQL ki official image pull karein
FROM mysql:8.0

# 2. Root password set karein (Zaroori hai)
ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# 3. (Optional) Ek database aur user pehle se bana dein
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# 4. MySQL default port 3306 par chalta hai
EXPOSE 3306